### ISSUE TITLE
Update to version 0.25.* and following

### ISSUE THREAD

**Issue by Jeanluc74** [Platoniq/decidim-module-comparative_stats#35]
Hello,

any update to the recent versions of decidim? 
This gem is really useful, it would be a pity to leave it unsupported.

Thank you,

Gian Luca

**Comment by fblupi** [comment]
@Jeanluc74 we are upgrading this gem to 0.25.x, 0.26.x and 0.27.x :)

**Comment by fblupi** [comment]
This gem has been successfully upgraded to 0.25. It will be upgraded to 0.26 and 0.27 in a few days.
